SCREEN_WIDTH = 1280 # pixels
SCREEN_HEIGHT = 720 # pixels
FPS = 60 # frames/second (duh)

ASTEROID_MIN_RADIUS = 20 # pixels
ASTEROID_KINDS = 3 
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20 #pixels
HITBOX_RADIUS = 15 #pixels
PLAYER_TURN_SPEED = 300 # degrees/second 300
PLAYER_MOVE_SPEED = 200 #pixels/second 200

SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.5

FONT_SIZE = 36

ITEM_RADIUS = 20
SHIELD_RADIUS = 40
